# Generated by Django 5.1.4 on 2024-12-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_list_delete_customuser_rename_completed_task_is_done_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='User',
            new_name='user',
        ),
    ]
